import React, { useState } from 'react';
import { Sparkles, Plus, ArrowUpRight } from 'lucide-react';
import { Overlay, Button, Icon, Insight } from './components.jsx';
import { PHASES, PHASE_NAMES, PhaseControls } from './board.jsx';

export function ProjectDetail({ project, data, close, perform, busy, propose, openTask, newTask, rollback, history, material, archive, demo }) {
  const [tab, setTab] = useState('goal'), [title, setTitle] = useState(project.title), [goal, setGoal] = useState(project.goal), [question, setQuestion] = useState(''), [from, setFrom] = useState(''), [to, setTo] = useState('');
  const tasks = data.tasks.filter((t) => t.projectId === project.id), records = data.records.filter((r) => r.projectId === project.id && !r.hidden), insights = data.insights.filter((i) => i.projectId === project.id), pending = data.proposals.filter((p) => p.projectId === project.id && ['running', 'ready', 'error'].includes(p.status));
  const save = () => perform('steward_project_update', { id: project.id, title, goal }, '项目目标已保存');
  const generate = async (type) => { if ((title !== project.title || goal !== project.goal) && !await save()) return; propose(project.id, type, undefined, { question, from, to }); };
  return <Overlay title={project.title} close={close} className="drawer project-drawer"><div className="drawer-body">
    <div className="detail-tabs" role="tablist">{Object.entries({ goal: '项目目标', tasks: '子任务', materials: '资料', insights: '问答与回顾' }).map(([id, label]) => <button key={id} role="tab" aria-selected={tab === id} onClick={() => setTab(id)}>{label}</button>)}</div>
    <PhaseControls item={project}/>
    {project.transitionId && <p className="setting-note">整个项目正在停止并回退，请稍候。</p>}
    {project.phase === 'done' && <div className="reopen-project"><p className="setting-note">追加新需求时重新打开，已有小卡阶段、聊天和成果保留。</p><Button kind="outline" disabled={busy || demo} onClick={() => perform('steward_project_reopen', { id: project.id }, '项目已重新打开，历史小卡阶段保留')}>重新打开并追加需求</Button></div>}
    {tab === 'goal' && <><label>项目名称<input value={title} maxLength={240} onChange={(e) => setTitle(e.target.value)}/></label><label>项目目标<textarea className="goal-text" value={goal} maxLength={30000} placeholder="长期目标、范围与预期成果…" onChange={(e) => setGoal(e.target.value)}/></label><div className="inline-actions"><Button kind="outline" disabled={busy || demo || !title.trim()} onClick={save}>保存目标</Button><Button kind="primary" disabled={busy || demo || !goal.trim()} onClick={() => generate('split')}><Icon as={Sparkles} size={16}/>AI 拆分目标</Button></div><p className="setting-note">AI 提出子任务方案，你挑选并修改后创建小卡。</p></>}
    {tab === 'tasks' && <><div className="section-heading"><h3>子任务 · {tasks.filter((t) => t.phase === 'done').length}/{tasks.length}</h3><Button kind="text" disabled={busy || demo || project.phase === 'done'} onClick={() => newTask(project.id)}><Icon as={Plus} size={16}/>新建子任务</Button></div>{tasks.map((t) => <button className="task-row" key={t.id} onClick={() => openTask(t.id)}><strong>{t.title}</strong><span>{PHASE_NAMES[t.phase]}</span></button>)}{!tasks.length && <p className="setting-note">先写下项目目标，让 AI 拟定子任务，或手动添加。</p>}<Button kind="outline" disabled={busy || demo} onClick={() => history(project.id)}>整理所选历史聊天</Button></>}
    {tab === 'materials' && <ProjectMaterials project={project} records={records} data={data} material={material} archive={archive} perform={perform} busy={busy} demo={demo}/>}
    {tab === 'insights' && <><form onSubmit={(e) => { e.preventDefault(); generate('question'); }}><label>项目问答<textarea value={question} maxLength={3000} placeholder="基于这个项目的资料提问…" onChange={(e) => setQuestion(e.target.value)}/></label><Button kind="primary" disabled={busy || demo || !question.trim()}><Icon as={Sparkles} size={16}/>提问</Button></form><h3>阶段回顾</h3><div className="field-pair"><label>开始日期<input type="date" value={from} onChange={(e) => setFrom(e.target.value)}/></label><label>结束日期<input type="date" value={to} onChange={(e) => setTo(e.target.value)}/></label></div><Button kind="outline" disabled={busy || demo} onClick={() => generate('review')}>生成回顾</Button>{insights.map((i) => <Insight key={i.id} item={i} records={data.records} tasks={tasks} actionsDisabled={busy || demo || project.phase === 'done'} openRecord={(id) => material(id, project.id)} addTodo={(action) => perform('steward_task_create', { projectId: project.id, title: action.title, description: action.content || action.title }, '建议已加入子任务')}/>)}</>}
    {pending.length > 0 && <section className="project-proposals"><h3>AI 建议</h3>{pending.map((p) => <button key={p.id} className="task-row" onClick={() => propose(project.id, null, null, { proposalId: p.id })}><strong>{{ split: '子任务拆分', criteria: '验收标准', history: '历史聊天归属', question: '项目问答', review: '阶段回顾' }[p.type]}</strong><span>{{ running: '正在生成', ready: '待确认', error: '生成失败' }[p.status]}</span></button>)}</section>}
  </div></Overlay>;
}

function ProjectMaterials({ project, records, data, material, archive, perform, busy, demo }) {
  const [selected, setSelected] = useState(new Set()), [query, setQuery] = useState(''), [filter, setFilter] = useState('all');
  const visible = records.filter((r) => (filter === 'all' || (filter === 'archived' ? r.archived : !r.archived)) && [r.title, r.content, r.summary, r.category, ...r.tags].join('\n').toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const jobs = data.jobs.filter((j) => j.type === 'archive' && j.recordIds.some((id) => records.some((r) => r.id === id)) && ['waiting', 'running', 'error'].includes(j.status));
  return <><div className="section-heading"><h3>项目资料</h3><Button kind="text" disabled={demo} onClick={() => material(null, project.id)}><Icon as={Plus} size={16}/>添加资料</Button></div>
    {records.length > 0 && <div className="materials-filter"><input aria-label="搜索项目资料" placeholder="搜索正文、分类或标签…" value={query} onChange={(e) => setQuery(e.target.value)}/><select aria-label="资料归档状态" value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">全部资料</option><option value="unarchived">未归档</option><option value="archived">已归档</option></select></div>}
    {records.some((r) => !r.archived) && <div className="inline-actions"><Button kind="outline" disabled={busy || demo || !records.some((r) => !r.archived && selected.has(r.id))} onClick={() => archive(records.filter((r) => !r.archived && selected.has(r.id)))}>批量归档 · {records.filter((r) => !r.archived && selected.has(r.id)).length}</Button></div>}
    {jobs.map((job) => <div className="archive-progress" key={job.id}><p>{job.status === 'error' ? job.error : `资料整理 ${job.done}/${job.total} · ${job.status === 'waiting' ? '等待 Codex 处理' : '正在整理'}`}</p>{job.status !== 'error' && <><progress value={job.done} max={job.total}/><Button kind="text" disabled={busy || demo} onClick={() => perform('steward_cancel_job', { jobId: job.id }, '已取消整理，已归档资料保留')}>取消整理</Button></>}</div>)}
    {visible.map((r) => <article key={r.id} className="material-row"><div className="material-heading">{!r.archived && <input aria-label={`选择资料：${r.title}`} type="checkbox" checked={selected.has(r.id)} onChange={(e) => { const next = new Set(selected); e.target.checked ? next.add(r.id) : next.delete(r.id); setSelected(next); }}/>}<button className="material-title" onClick={() => material(r.id, project.id)}><h4>{r.title}</h4></button></div><p>{r.summary || r.content}</p>{r.archived && <><div className="material-tags">{[r.category, ...r.tags].filter(Boolean).map((tag, i) => <span key={i}>{tag}</span>)}</div>{r.keypoints.length > 0 && <ul className="material-points">{r.keypoints.map((point, i) => <li key={i}>{point}</li>)}</ul>}</>}
      {(r.suggestedActions || []).map((action, index) => { const key = action.title.replace(/\s+/g, '').toLowerCase(), added = data.tasks.some((t) => t.sourceRecordId === r.id && t.sourceActionKey === key); return <div className="suggested-action" key={index}><div><strong>{action.title}</strong>{action.content && <p>{action.content}</p>}</div><Button kind="text" disabled={busy || demo || added || project.phase === 'done'} onClick={() => perform('steward_accept_actions', { id: r.id, expectedUpdatedAt: r.updatedAt, indexes: [index] }, '建议已加入灵感小卡')}>{added ? '已加入' : '确认加入小卡'}</Button></div>; })}
      <div className="material-actions">{r.sourceChatId && <a href={`codex://threads/${encodeURIComponent(r.sourceChatId)}`}>来源聊天<Icon as={ArrowUpRight} size={14}/></a>}<Button kind="text" disabled={busy || r.archived || demo} onClick={() => archive(r)}>{r.archived ? '已归档' : 'AI 归档'}</Button><Button kind="text" disabled={busy || demo} onClick={() => perform('steward_material_hide', { id: r.id, projectId: project.id }, '已从项目资料移除')}>移除</Button></div></article>)}
    {!records.length && <p className="setting-note">精选成果、关键决定与可复用结论会从主聊天沉淀到这里，并保留来源。</p>}</>;
}

export function NewItem({ kind, projectId, close, perform, busy, created }) {
  const [title, setTitle] = useState(''), [content, setContent] = useState('');
  return <Overlay title={kind === 'project' ? '新建项目' : '新建子任务'} close={close}><form onSubmit={async (e) => { e.preventDefault(); const result = await perform(kind === 'project' ? 'steward_project_create' : 'steward_task_create', kind === 'project' ? { title, goal: content } : { projectId, title, description: content }, kind === 'project' ? '项目已创建' : '子任务已创建'); if (result) created(result); }}><label>{kind === 'project' ? '项目名称' : '任务名称'}<input required maxLength={240} value={title} placeholder={kind === 'project' ? '一个长期项目…' : '一件可执行的事…'} onChange={(e) => setTitle(e.target.value)}/></label><label>{kind === 'project' ? '项目目标' : '任务说明'}<textarea className="goal-text" value={content} maxLength={30000} placeholder="描述目标、范围与预期成果…" onChange={(e) => setContent(e.target.value)}/></label><div className="dialog-actions"><Button kind="outline" type="button" onClick={close}>取消</Button><Button kind="primary" disabled={busy || !title.trim()}>创建</Button></div></form></Overlay>;
}

export function Rollback({ project, expectedPhase = project.phase, tasks, close, perform, busy, done }) {
  const children = tasks.filter((t) => t.projectId === project.id), phase = PHASES[PHASES.indexOf(expectedPhase) - 1];
  return <Overlay title="回退整个项目" close={close}><p>「{project.title}」将回到{PHASE_NAMES[phase]}。所属 <strong>{children.length} 张小卡全部停止执行，统一回到待启动</strong>，包括已结项的小卡。</p><p className="setting-note">聊天、已有成果和项目资料保留。</p><div className="rollback-list">{children.map((t) => <div key={t.id}><span>{t.title}</span><span>{PHASE_NAMES[t.phase]} → 待启动</span></div>)}</div><div className="dialog-actions"><Button kind="outline" disabled={busy} onClick={close}>取消</Button><Button kind="primary" disabled={busy} onClick={async () => { if (await perform('steward_project_move', { id: project.id, phase, expectedPhase }, '整个项目已回退')) done(); }}>{busy ? '正在停止并回退…' : '停止并回退全部小卡'}</Button></div></Overlay>;
}

export function MaterialEdit({ record, projectId, close, perform, busy }) {
  const [title, setTitle] = useState(record?.title || ''), [content, setContent] = useState(record?.content || '');
  return <Overlay title={record ? '资料详情' : '添加项目资料'} close={close}><form onSubmit={async (e) => { e.preventDefault(); const result = await perform(record ? 'steward_update' : 'steward_create', record ? { id: record.id, patch: { title, content } } : { type: 'material', title, content, projectId }, '资料已保存'); if (result) close(); }}><label>标题<input required maxLength={240} value={title} onChange={(e) => setTitle(e.target.value)}/></label><label>正文<textarea className="material-text" required maxLength={60000} value={content} onChange={(e) => setContent(e.target.value)}/></label>{record?.hidden && <p className="setting-note">此资料已从项目列表移除，保留正文用于历史引用。</p>}{record?.sourceChatId && <a href={`codex://threads/${encodeURIComponent(record.sourceChatId)}`}>来源聊天</a>}<div className="dialog-actions"><Button kind="primary" disabled={busy || !content.trim() || !title.trim()}>保存资料</Button></div></form></Overlay>;
}
