import React, { useState, useEffect } from 'react';
import { Overlay, Button, Icon } from './components.jsx';
import { LoaderCircle, Check, ArrowUpRight } from 'lucide-react';
import { call } from './bridge.js';

export function Proposal({ proposal, data, close, perform, busy, applied }) {
  const [tasks, setTasks] = useState(() => proposal.result?.tasks?.map((t) => ({ ...t, selected: true })) || []), [criteria, setCriteria] = useState(proposal.result?.criteria?.join('\n') || ''), [assignments, setAssignments] = useState(proposal.result?.assignments?.map((a) => ({ ...a, selected: true })) || []);
  useEffect(() => { if (proposal.status !== 'ready') return; setTasks(proposal.result?.tasks?.map((t) => ({ ...t, selected: true })) || []); setCriteria(proposal.result?.criteria?.join('\n') || ''); setAssignments(proposal.result?.assignments?.map((a) => ({ ...a, selected: true })) || []); }, [proposal.id, proposal.status]);
  const labels = { split: '确认子任务方案', criteria: '确认验收标准草案', question: '项目问答', review: '阶段回顾', history: '确认历史聊天归属' };
  const apply = async () => { const args = { id: proposal.id }; if (proposal.type === 'split') args.tasks = tasks.filter((t) => t.selected).map(({ selected, ...t }) => ({ ...t, criteria: t.criteria.map((c) => c.trim()).filter(Boolean) })); if (proposal.type === 'criteria') args.criteria = criteria.split('\n').map((c) => c.trim()).filter(Boolean); if (proposal.type === 'history') args.assignments = assignments.filter((a) => a.selected).map(({ selected, ...a }) => a); const result = await perform('steward_apply_proposal', args, '已保存你的选择'); if (result) applied(proposal); };
  return <Overlay title={labels[proposal.type]} close={close} className="proposal-dialog">
    {proposal.status === 'running' && <><div className="generating"><Icon as={LoaderCircle} className="spin"/><p>Codex 正在拟定建议</p><span>可以关闭窗口，稍后从项目详情继续查看。</span></div><div className="dialog-actions"><Button kind="outline" disabled={busy || !proposal.turnId} onClick={() => perform('steward_cancel_proposal', { id: proposal.id }, '已停止生成')}>停止生成</Button></div></>}
    {proposal.status === 'error' && <p className="inline-error" role="alert">{proposal.error}</p>}
    {proposal.status === 'cancelled' && <p className="setting-note">已停止生成，资料没有变动。</p>}
    {proposal.status === 'ready' && <>
      {proposal.type === 'split' && <><p className="setting-note">挑选需要的子任务，可以修改名称、说明和验收标准。创建后仍需在各小卡确认标准才启动。</p>{tasks.map((task, index) => <section className="proposal-task" key={index}><label className="checkbox-label"><input type="checkbox" checked={task.selected} onChange={(e) => setTasks(tasks.map((t, i) => i === index ? { ...t, selected: e.target.checked } : t))}/>保留此子任务</label><label>名称<input value={task.title} maxLength={240} onChange={(e) => setTasks(tasks.map((t, i) => i === index ? { ...t, title: e.target.value } : t))}/></label><label>说明<textarea value={task.description} onChange={(e) => setTasks(tasks.map((t, i) => i === index ? { ...t, description: e.target.value } : t))}/></label><label>验收标准<textarea value={task.criteria.join('\n')} onChange={(e) => setTasks(tasks.map((t, i) => i === index ? { ...t, criteria: e.target.value.split('\n') } : t))}/></label></section>)}</>}
      {proposal.type === 'criteria' && <><p className="setting-note">检查并编辑草案。保存后，在小卡中勾选确认才允许启动。</p><label>验收标准<textarea className="criteria-text" value={criteria} onChange={(e) => setCriteria(e.target.value)}/></label></>}
      {proposal.type === 'history' && <><p className="setting-note">确认每个聊天的项目与小卡归属。可修改建议，或取消勾选暂不处理的聊天。</p>{assignments.map((a, index) => {
        const update = (patch) => setAssignments(assignments.map((v, i) => i === index ? { ...v, ...patch } : v));
        return <section className="proposal-task" key={a.chatId}><label className="checkbox-label"><input type="checkbox" checked={a.selected} onChange={(e) => update({ selected: e.target.checked })}/>关联此聊天</label><a href={`codex://threads/${encodeURIComponent(a.chatId)}`}>查看来源聊天<Icon as={ArrowUpRight} size={15}/></a><label>目标项目<select value={a.projectId || ''} onChange={(e) => update({ projectId: e.target.value || null, taskId: null })}><option value="">新建项目</option>{data.projects.map((p) => <option key={p.id} value={p.id}>{p.title}</option>)}</select></label>{!a.projectId && <label>新项目名称<input value={a.projectTitle} maxLength={240} onChange={(e) => update({ projectTitle: e.target.value })}/></label>}<label>目标子任务<select value={a.taskId || ''} onChange={(e) => update({ taskId: e.target.value || null })}><option value="">新建小卡</option>{data.tasks.filter((t) => t.projectId === a.projectId).map((t) => <option key={t.id} value={t.id}>{t.title}</option>)}</select></label>{!a.taskId && <><label>任务名称<input value={a.title} maxLength={240} onChange={(e) => update({ title: e.target.value })}/></label><label>任务说明<textarea value={a.description} maxLength={30000} onChange={(e) => update({ description: e.target.value })}/></label></>}</section>;
      })}</>}
      {['question', 'review'].includes(proposal.type) && <><div className="answer">{proposal.result.answer}</div><h3>引用来源</h3>{proposal.result.sources.map((s, i) => <div className="source-item" key={i}><strong>[{i + 1}] {data.records.find((r) => r.id === s.recordId)?.title || s.recordId}</strong><p>{s.note}</p></div>)}</>}
      <div className="dialog-actions"><Button kind="outline" onClick={close}>稍后处理</Button><Button kind="primary" disabled={busy || proposal.type === 'split' && !tasks.some((t) => t.selected) || proposal.type === 'criteria' && !criteria.trim() || proposal.type === 'history' && (!assignments.some((a) => a.selected) || assignments.some((a) => a.selected && ((!a.projectId && !a.projectTitle.trim()) || (!a.taskId && !a.title.trim()))))} onClick={apply}>{proposal.type === 'split' ? '确认并创建小卡' : proposal.type === 'history' ? '确认关联' : '保存到项目'}</Button></div>
    </>}
  </Overlay>;
}

export function ChatPicker({ taskId, projectId, close, perform, busy, propose, notify }) {
  const [threads, setThreads] = useState([]), [cursor, setCursor] = useState(null), [search, setSearch] = useState(''), [selected, setSelected] = useState(new Set()), [loading, setLoading] = useState(false), [main, setMain] = useState(false);
  const fetchThreads = async (append = false) => { setLoading(true); try { const result = await call('steward_chats', { search, ...(append && cursor ? { cursor } : {}) }); setThreads(append ? [...threads, ...result.threads] : result.threads); setCursor(result.nextCursor); } catch (error) { notify(error.message); } finally { setLoading(false); } };
  useEffect(() => { fetchThreads(); }, []);
  const submit = async () => { if (taskId) { for (const chatId of selected) if (!await perform('steward_chat_attach', { taskId, chatId, main }, '聊天已关联')) return; close(); } else propose(projectId, 'history', undefined, { chatIds: [...selected] }); };
  return <Overlay title={taskId ? '关联已有聊天' : '选择历史聊天'} close={close}><form className="chat-search" onSubmit={(e) => { e.preventDefault(); fetchThreads(); }}><input aria-label="搜索已有聊天" placeholder="搜索聊天标题…" value={search} onChange={(e) => setSearch(e.target.value)}/><Button kind="outline" disabled={loading}>搜索</Button></form><p className="setting-note">只整理你勾选的聊天，每次最多 30 个。</p><div className="chat-picker">{threads.map((t) => <label className="chat-option" key={t.id}><input type={main ? 'radio' : 'checkbox'} checked={selected.has(t.id)} onChange={(e) => { const next = main ? new Set() : new Set(selected); if (e.target.checked) next.add(t.id); else next.delete(t.id); setSelected(next); }}/><span>{t.title}</span></label>)}</div>{loading && <p className="setting-note">正在读取聊天列表…</p>}{cursor && <Button kind="text" disabled={loading} onClick={() => fetchThreads(true)}>加载更多</Button>}{taskId && <label className="checkbox-label"><input type="checkbox" checked={main} onChange={(e) => { setMain(e.target.checked); setSelected(new Set()); }}/>作为主聊天（仅限尚未执行的小卡）</label>}<div className="dialog-actions"><Button kind="outline" onClick={close}>取消</Button><Button kind="primary" disabled={busy || selected.size < 1 || selected.size > 30} onClick={submit}>{taskId ? '确认关联' : 'AI 建议归属'}</Button></div></Overlay>;
}
